
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Check test result
        run: |
          if [ $? -eq 0 ]; then
            echo "Tests passed!"
            exit 0
          else
            echo "Tests failed!"
            exit 1
          

